### ISSUE TITLE
关于RIME方案的修改

### ISSUE THREAD

**Issue by lantyu** [zecy/flypy_double#1]
非常感谢大神编写的鹤形方案，我现在就是借鉴您的这个方案在使用。

不过由于刚刚接触，所以在修改方案的过程中稍微有点地方我不知道如何进行修改。

我目前想实现提示码的逐键提示，也就是随着输入的码的增多，匹配的字符的提示码减少

如 “神” 编码为ufpu， 我现在无论打上什么码都是显示的ufpu，我想实现的是，当我输入u之后，提示码只显示fpu，当我输入uf后，提示码只显示pu

新人不太清楚这个怎么实现，希望有空能指教。谢谢

**Comment by zecy** [comment]
要实现逐渐提示你需要

1. 在 translator 中设置 enable_completion: true ；
2. 把用户词典关闭，设置 enable_user_dict: false ；
3. 把 engine 项下的 translator 中 script_translator 改为 table_translator 。

这样就能实现逐渐提示。但会有以下问题：

1. 关闭了用户词典，你不能自组词了。如果不关闭用户词典，候选项中你的字组词会靠前，逐键提示没有什么用。
2. 提示在词是根据码表顺序排列的，即你输入「 u 」后，提示项会是「 ua 」「 ub 」「 uc 」这样排列下去，你输入「 uf
」后，候选项中会出现「 ufa 」「 ufb 」……而「 ufp 」会出现在很后面，同时「 ufpu 」会在「 ufpa 」等后面出现实际意义不大。

又因为使用的是 table_translator ，所以你是无法进行自动调频的。要如何选择就看你哪方面的需求更强了。

在 2017年2月6日 下午2:58，li_zongxing <notifications@github.com>写道：

**Comment by lantyu** [comment]
学习了，受益匪浅

太感谢了，困扰了我很久的问题
